# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Test

on: [push, pull_request]

jobs:
  validate:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-18.04
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: wordpress_test
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Install PHP
        uses: shivammathur/setup-php@2.7.0
        with:
          php-version: 7.4
          extensions: mysqli, xmlwriter
          coverage: none
        env:
          fail-fast: true

      - name: Debugging
        run: |
          php --version
          php -m
          composer --version

      - run: npm install
      - run: composer install

      - run: composer run test
        env:
          WP_TESTS_DB_HOST: 127.0.0.1:${{ job.services.mysql.ports['3306'] }}
